### ISSUE TITLE
Java concept scraping is not working

### ISSUE THREAD

**Issue by mestar89** [smamusa/exchange-rate-scraper#3]
The parser doesn't seem to able to render JS code, this should be a priority. @smamusa pls check this asap so we can continue building the scraper

**Comment by smamusa** [comment]
I'll get on this tomorrow, tnx for your input. 🙂

**Comment by smamusa** [comment]
It appears to be working fine now, if you could test in your machine it would be great.

1.  Checkout **java-concept** branch
2.  Run **mvn package**
3.  The run **java -jar exchange-rate-scraper-1.0-SNAPSHOT-jar-with-dependencies.jar**

_Make sure you have Java 17 set on JAVA_PATH, otherwise it will fail, also run the terminal as admin_
